title: TBC V2 Docs
description: Documentation for Twitch Badge Collector V2
theme: just-the-docs

url: "https://tbc2.bluewarn.dev"
logo: "https://cdn.jsdelivr.net/gh/Deepbluewarn/twitch_badge_collector_web@fcdcd297de5497c3adfad05d0115f41976d12728/src/public/logo/TBC%20400.png"
favicon_ico: "https://cdn.jsdelivr.net/gh/Deepbluewarn/twitch_badge_collector_web@fcdcd297de5497c3adfad05d0115f41976d12728/src/public/favicon/favicon.ico"
callouts:
  warning:
    title: 경고
    color: red

aux_links:
  Discord: https://discord.gg/ZM6Eazpz5V
  Github: https://github.com/Deepbluewarn/twitch-badge-collector-v2
  Email: mailto:tbcextension@gmail.com
