title: TBC V2 Docs
description: Documentation for Twitch Badge Collector V2
theme: just-the-docs

url: https://bluewarndev.github.io

aux_links:
  Discord: https://discord.gg/ZM6Eazpz5V
  Github: https://github.com/Deepbluewarn/twitch-badge-collector-v2
  Email: tbcextension@gmail.com
