title: TBC V2 Docs
description: Documentation for Twitch Badge Collector V2
theme: just-the-docs

url: https://bluewarndev.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
